name: Deploy Frontend
on:
  push:
    branches: [ main ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          api_location: ""
          output_location: "build"
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          NEXT_PUBLIC_AZURE_FUNCTION_KEY: ${{ secrets.AZURE_FUNCTION_KEY }}